# -*- coding: utf-8 -*-
"""SkewT_wrf.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NrfMMkUUgVb2cjgxvKGzmhyZ4vb14cZS

# New Section
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install netCDF4

filename='/content/drive/MyDrive/Meteorologia_UFSC/11_Fase/Meso/seminario2/wrfout_d02_2020-08-14_00_00_00'

!git clone https://github.com/cwebster2/pyMeteo.git

cd pyMeteo

!python3 setup.py install

cd /content/pyMeteo/

import numpy as np
import pymeteo.skewt as skewt
import pymeteo
import netCDF4

!ls

pymeteo.skewt.plot_wrf(filename, -27.05, -51.18, 40, 'output.pdf')

ls

pwd

cp /content/pyMeteo/output.pdf /content/drive/MyDrive/Meteorologia_UFSC/11_Fase/Meso/seminario2/output_d02_2000.pdf

